### ISSUE TITLE
how can I get the .pth files in cfg？

### ISSUE THREAD

**Issue by bianlongpeng** [lxztju/pytorch_classification#1]
![image](https://user-images.githubusercontent.com/22487109/79708920-62888780-82f3-11ea-8748-05183143c6e2.png)
nice to learnning your project, but a question is how can I get the ‘.pth’ files as pic's

**Comment by bianlongpeng** [comment]
> ![image](https://user-images.githubusercontent.com/22487109/79708920-62888780-82f3-11ea-8748-05183143c6e2.png)
> nice to learnning your project, but a question is how can I get the ‘.pth’ files as pic's

I known

**Comment by lxztju** [comment]
You could find the url from build_model.py

**Comment by bianlongpeng** [comment]
> You could find the url from build_model.py

yes， I find it，thanks！
