### ISSUE TITLE
训练没报错但是运行一半结束了

### ISSUE THREAD

**Issue by QISIRUI** [lxztju/pytorch_classification#10]
torch1.4.0 torchvision0.5.0

当运行train.py的时候，没有报错但是程序运行一半结束了

>****** Training resnet101 ******
>****** loading the Imagenet pretrained weights ******
>****** using single gpu to training ********
>...... Initialize the network done!!! .......
>Process finished with exit code 0

程序输出到这里就结束了，可以指点一下吗

**Comment by lxztju** [comment]
torch1.4.0 torchvision0.5.0，这个环境可以用，我最近刚用过
这个问题可能是存在异常捕捉try except，数据格式不对然，后跳过了所有的数据
或者是最大迭代次数没有设置好，直接没有进入循环。
第一种可能大一点

**Comment by QISIRUI** [comment]
输入图片是jpg格式，灰度图像，INPUT_SIZE是指300x300的图像吗
>INPUT_SIZE = 300

换了彩色图像数据后可以接着运行（也不是300x300）

但是出现这个错误
>AttributeError: Can't pickle local object 'get_random_eraser.<locals>.eraser'
看前人解决办法是注释掉图像增广函数，加行代码

但不知道是注释掉哪里

**Comment by QISIRUI** [comment]
> torch1.4.0 torchvision0.5.0，这个环境可以用，我最近刚用过
> 这个问题可能是存在异常捕捉try except，数据格式不对然，后跳过了所有的数据
> 或者是最大迭代次数没有设置好，直接没有进入循环。
> 第一种可能大一点

后续将图片换成彩色的数据集后可以接着运行，但也出现这个问题
`AttributeError: Can't pickle local object 'get_random_eraser.<locals>.eraser'`
不知道哪一部分是图像增广函数，请问是注释掉哪一部分呢

**Comment by sky-fly97** [comment]
> > Torch1.4.0 Torchvision0.5.0，这个环境可以用，我最近刚用过这个问题可能是存在异常捕捉尝试除外，数据格式不对然，后跳过了所有的数据或者是最大迭代次数没有设置好，直接没有进入循环.第一种可能大一点
> 
> 后续将图片换成彩色的数据集后可以接着运行，但也出现这个问题
> 追溯(最近一次调用)：
> 文件“F:/6-pycode/1-SVM/pytorch_classification-master/train.py”，第116行，在
> 批迭代器=ITER(列车数据处理机)
> `AttributeError: Can't pickle local object 'get_random_eraser.<locals>.eraser'`
> 不知道是不是图像增广函数的问题，是的话请问是注释掉哪一部分呢

我也是一样的问题，请问您解决了吗

**Comment by QISIRUI** [comment]
这个因为数据集太小了，所以没运行完就结束了
