### ISSUE TITLE
出现错误ValueError: optimizer got an echuxian mpty parameter list

### ISSUE THREAD

**Issue by Shank2358** [lxztju/pytorch_classification#13]
在加载完模型之后出现错误ValueError: optimizer got an empty parameter list

定位到的报错位置是
 File "train.py", line 76, in <module>
    optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=cfg.LR)

**Comment by lxztju** [comment]
这是优化器定义时，不小心写错了模型的名字，已经改过来

**Comment by Shank2358** [comment]
嗯嗯谢谢，我也按照那个修改了。现在出现了另外一个问题就是初始化模型之后直接结束了，GPU也没有启动，我检查了一下数据格式和dataloader好像没有问题（我之前怀疑是数据错误导致抛出异常），检查了一下发现加载数据都是正常的，请问您有遇到过这样的情况吗，我在另外一个issue里面也看到了类似问题。谢谢。
![image](https://user-images.githubusercontent.com/33946139/89709278-0e440900-d9b1-11ea-9885-206bc17bd48c.png)

**Comment by PngYng** [comment]
> 在加载完模型之后出现错误ValueError: optimizer got an empty parameter list
> 
> 定位到的报错位置是
> File "train.py", line 76, in
> optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=cfg.LR)

你好请问这个具体在哪里修改呀，我没找见，出现了同样的错误

**Comment by PngYng** [comment]
> 这是优化器定义时，不小心写错了模型的名字，已经改过来

你好请问这个具体在哪里修改呀，我没找见，出现了同样的错误

**Comment by DnYoZn** [comment]
> > 这是优化器定义时，不小心写错了模型的名字，已经改过来
> 
> 你好请问这个具体在哪里修改呀，我没找见，出现了同样的错误

你这个问题解决了吗

**Comment by dmuqlzhang** [comment]
> > > 这是优化器定义时，不小心写错了模型的名字，已经改过来
> > 
> > 
> > 你好请问这个具体在哪里修改呀，我没找见，出现了同样的错误
> 
> 你这个问题解决了吗

已解决问题，train.py 43行param.requires_grad = False，将False改为True即可正常训练
