### ISSUE TITLE
使用dataloader时加载数据集时出现错误

### ISSUE THREAD

**Issue by BarryAlanPan** [lxztju/pytorch_classification#5]
<img width="669" alt="image" src="https://user-images.githubusercontent.com/44538391/86448579-859ad300-bd49-11ea-9155-062523ce49d1.png">
主要错误集中在“AttributeError: Can't pickle local object 'get-random-eraser.<locals>.eraser'”

**Comment by lxztju** [comment]
你的图片不能正确显示，我刚测试过没有问题，你可以自己调试一下看看那个地方出错了

**Comment by BarryAlanPan** [comment]
我在注释掉增广函数后，增加一行转换解决了后续的输出问题：
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/44538391/86479393-a7627d00-bd7e-11ea-8783-9e0689a11224.png">

**Comment by QISIRUI** [comment]
> 我在注释掉增广函数后，增加一行转换解决了后续的输出问题：
> <img alt="image" width="1150" src="https://user-images.githubusercontent.com/44538391/86479393-a7627d00-bd7e-11ea-8783-9e0689a11224.png">
我也遇到同样的问题，请问是注释掉哪里呢

**Comment by sky-fly97** [comment]
+1，我也遇到一样的问题

**Comment by sky-fly97** [comment]
> 我在注释掉增广函数后，增加一行转换解决了后续的输出问题：
> <img alt="image" width="1150" src="https://user-images.githubusercontent.com/44538391/86479393-a7627d00-bd7e-11ea-8783-9e0689a11224.png">

棒！ 解决了

**Comment by QISIRUI** [comment]
> +1，我也遇到一样的问题

你是怎么解决的啊

**Comment by sky-fly97** [comment]
> > +1，我也遇到一样的问题
> 
> 你是怎么解决的啊
注释掉即可
`# 相关预处理的初始化
      #  self.transforms=transform
        self.img_aug=True

        self.transform= get_train_transform(size=cfg.INPUT_SIZE)
        # self.eraser = get_random_eraser( s_h=0.1, pixel_level=True)
        self.input_size = cfg.INPUT_SIZE`

**Comment by QISIRUI** [comment]
然而，我还是出现另一个问题@sky-fly97 
![pybug1](https://user-images.githubusercontent.com/48178028/88453998-a5cc3680-ce9e-11ea-9a86-c9a547995a0d.png)
也不知道是不是和数据集格式有关

**Comment by thevolga** [comment]
> 然而，我还是出现另一个问题@sky-fly97
> ![pybug1](https://user-images.githubusercontent.com/48178028/88454035-f8a5ee00-ce9e-11ea-8b0b-9dc68a424d34.png)
> 
> 也不知道是不是和数据集格式有关

同出现这个问题 请问解决了吗
