### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by Joe-Mikey** [lxztju/pytorch_classification#8]
求请教！
在跑代码时报错：ValueError: too many values to unpack (expected 2)
定位到时data文件夹下的dataset.py，而后尝试仅允许该文件dataset.py测试数据提取函数，发现仍然报相同的错
![image](https://user-images.githubusercontent.com/56524467/87040807-d87dfa00-c223-11ea-89cf-9085fd448e65.png)

**Comment by lxztju** [comment]
这个你可以查看一下对应的等号右边和左边的分别是什么，简爱男单调试一下代码

**Comment by Joe-Mikey** [comment]
感谢！！原因找到了，是我的数据处理问题。

**Comment by SCU-XU** [comment]
> 感谢！！原因找到了，是我的数据处理问题。
你好，请问你怎么解决的问题呀，我的跑代码报错跟你一样的，我以为是数据集的文件格式和生成的txt路径文件的问题，我的理解是本来有train,test两个文件夹，里面分别有n个文件夹，分别有不同类别的图片。然后preprocress.py生成的有train,test,val三个txt文件，里面都有绝对路径和相应的标签。请问，我的数据设置格式对吗？同时也想请教下你具体遇到的问题和解决方法。
